spring:
  application:
    name: MVC_MegaNet

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 08051992
    url: jdbc:postgresql://localhost:5432/meganet_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090

logging:
  level:
    root: info
  file:
    name: logs/application.log

  logback:
    rolling policy:
      max-file-size: 3MB
      max-history: 3
      total-size-cap: 9MB